---
test_environment: #测试环境的地址
    url: "http://211.103.136.242:8064"

LOG:
  log_level: "debug"  #log登录
  log_extensiong: ".log"  #扩展名

test_environment1: #测试环境的地址
    url: "http://211.103.136.242:8064"

BASE:
  case_file: "testdata.xlsx"
  case_sheet: "美多商城接口测试"


email:
  smtpserver: "smtp.qq.com"
  username: "1315270232@qq.com"
  password: "shqwihtlifxojheg"
  receiver: "314983713@qq.com"