---
test_login:
  url: "http://192.168.1.202:8117/#/Login"
  url_ip: "http://192.168.1.202:8117/#/"
  url1: "用不着的http://192.168.1.202:8117/#/Login"
  text: "admin"
  password: "admin"
  validation_url: "http://tp.safetycms.huayustech.com"
  new_url: "http://192.168.1.202:8117/#/Login"
  SCHOOL: "moxicheng zzl123"

test_school_management_add:
  school_name: "会同三中"
  describe: "会同三中描述"

test_school_management_inquire:
  inquire_content: "学校22"

test_school_management_alter:
  school_name: "会同三中"
  describe: "会同三中描述"


Test_course_add:
