---
test_login:
  url: "http://192.168.1.202:8117/#/Login"
  url_ip: "http://192.168.1.202:8117/#/"
  url1: "用不着的http://192.168.1.202:8117/#/Login"
  text: "admin"
  password: "admin"
  validation_url: "http://tp.safetycms.huayustech.com"
  new_url: "http://192.168.1.202:8117/#/Login"
  SCHOOL: "moxicheng zzl123"





test_school_management_add:
  module_name: "学校管理"
  test_name: "学校管理添加"
  school_name: "会同三中"
  describe: "会同三中描述"

test_school_management_inquire:
  module_name: "学校管理"
  test_name: "学校管理查询"
  inquire_content: "学校22"
  inquire_field: "学校管理-学校名称"

test_school_management_alter:
  module_name: "学校管理"
  test_name: "学校管理查询"
  school_name: "会同三中"
  describe: "会同三中描述"

test_school_management_del:
  module_name: "学校管理"

